# Generated by Django 3.1.6 on 2021-02-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SupportContacts',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(blank=True, max_length=16, null=True)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'support_contacts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SupportRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=16, null=True)),
                ('type', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('subject', models.CharField(blank=True, max_length=64, null=True)),
                ('message', models.CharField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'db_table': 'support_requests',
                'managed': True,
            },
        ),
    ]
