# Generated by Django 3.1.6 on 2021-02-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequests',
            name='contact_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
