# Generated by Django 3.1.7 on 2021-02-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_effort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletypes',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
