# Generated by Django 3.1.7 on 2021-03-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportcontacts',
            old_name='name',
            new_name='type_name',
        ),
        migrations.RemoveField(
            model_name='supportcontacts',
            name='type',
        ),
    ]
