# Generated by Django 3.1.7 on 2021-03-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_remove_supportrequests_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequests',
            name='contact_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
