# Generated by Django 3.1.7 on 2021-03-16 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRCVisit',
            fields=[
                ('crc_id', models.AutoField(primary_key=True, serialize=False)),
                ('calendar_screen', models.FloatField(blank=True, null=True)),
                ('chart_review', models.FloatField(blank=True, null=True)),
                ('pre_cert', models.FloatField(blank=True, null=True)),
                ('consent', models.FloatField(blank=True, null=True)),
                ('eligibility_checklist', models.FloatField(blank=True, null=True)),
                ('registration', models.FloatField(blank=True, null=True)),
                ('ivrs_iwrs', models.FloatField(blank=True, null=True)),
                ('scheduling', models.FloatField(blank=True, null=True)),
                ('medical_history', models.FloatField(blank=True, null=True)),
                ('vitals', models.FloatField(blank=True, null=True)),
                ('lab_work', models.FloatField(blank=True, null=True)),
                ('imaging', models.FloatField(blank=True, null=True)),
                ('ecgs', models.FloatField(blank=True, null=True)),
                ('oral_medication', models.FloatField(blank=True, null=True)),
                ('clinic_notes', models.FloatField(blank=True, null=True)),
                ('billing', models.FloatField(blank=True, null=True)),
                ('crf_entry', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crc_visit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CTEffort',
            fields=[
                ('cte_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('estimated_accruals', models.IntegerField(blank=True, null=True)),
                ('pi_effort', models.FloatField(blank=True, null=True)),
                ('pi_effort_copy', models.BooleanField(default=False)),
                ('monitor_days', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'effort_models',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cycles',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_cycles', models.IntegerField(blank=True, null=True)),
                ('number_visits', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('copy_hours', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cycles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CycleTypes',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'cycle_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DCVisit',
            fields=[
                ('dcv_id', models.AutoField(primary_key=True, serialize=False)),
                ('infusion', models.FloatField(blank=True, null=True)),
                ('pk_samples', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dc_visit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GeneralVisit',
            fields=[
                ('gv_id', models.AutoField(primary_key=True, serialize=False)),
                ('training', models.FloatField(blank=True, null=True)),
                ('protocol_review', models.FloatField(blank=True, null=True)),
                ('source_document', models.FloatField(blank=True, null=True)),
                ('regulatory', models.FloatField(blank=True, null=True)),
                ('sponsor_meetings', models.FloatField(blank=True, null=True)),
                ('internal_meetings', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'g_visit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NCVisit',
            fields=[
                ('ncv_id', models.AutoField(primary_key=True, serialize=False)),
                ('infusion', models.FloatField(blank=True, null=True)),
                ('pk_samples', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nc_visit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonnelTypes',
            fields=[
                ('pt_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'personnel_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrialArms',
            fields=[
                ('ta_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_effort.cteffort')),
            ],
            options={
                'db_table': 'trial_arms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('arm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinical_effort.trialarms')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_effort.cycles')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_effort.cteffort')),
            ],
            options={
                'db_table': 'visits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_effort.cteffort')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_effort.personneltypes')),
            ],
            options={
                'db_table': 'visit_personnel',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cycles',
            name='arm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinical_effort.trialarms'),
        ),
        migrations.AddField(
            model_name='cycles',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_effort.cteffort'),
        ),
        migrations.AddField(
            model_name='cycles',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_effort.cycletypes'),
        ),
    ]
