# Generated by Django 3.1.7 on 2021-02-22 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_effort', '0002_cycletypes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycles',
            name='arm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinical_effort.trialarms'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='arm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinical_effort.trialarms'),
        ),
    ]
